osx_image: xcode9.2
language: swift

branches:
  only:
  - /^snapshot.*/

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install -g firebase-tools

deploy:
  - provider: script
    script:
      - bundle exec fastlane snapshot
      - cp fastlane/screenshots/screenshots.html functions/templates/index.html
      - cp -r fastlane/screenshots/ja-JP public
      - cd functions && npm i && cd ..
      - firebase deploy --token $FIREBASE_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH =~ ^snapshot.*'
