osx_image: xcode9.2
language: swift

branches:
  only:
  - /^snapshot.*/

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

deploy:
  - provider: script
    script: ./firebase_deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH =~ ^snapshot.*'
