osx_image: xcode9.2
language: swift

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install -g firebase-tools

script:
  - bundle exec fastlane snapshot

after_success:
  - cp fastlane/screenshots/screenshots.html public/index.html
  - cp -r fastlane/screenshots/ja-JP public
  - firebase deploy --token $FIREBASE_TOKEN
